name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '1.Update the version information in package.json and manifest.json 2.Input a new version such as 0.0.1 below to release'
        required: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: shortcuts-guard.zip

      - name: Check Input Tag
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        env:
          TAG: v${{github.event.inputs.version}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        if: steps.checkTag.outputs.exists == 'false'
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ github.event.inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'

      - name: Create Changelog
        if: steps.checkTag.outputs.exists == 'false'
        id: create_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: '.github/changelog-configuration.json'

      - name: Release
        if: steps.checkTag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.create_changelog.outputs.changelog }}
          files: |
            shortcuts-guard.zip
          tag_name: v${{github.event.inputs.version}}
